1- Create three lists representing house features, each list containing ten values. The first one for the house's size in square meters, the second one for rooms and last for price. Then, create an array combining these lists.

In [5]:
import numpy as np
size = [200,250,350,290,310,259,300,180,220,400]
rooms = [2,3,3,3,3,3,4,2,3,5]
price = [180,190,240,200,230,195,250,160,210,300]
features = np.array([size,rooms,price])
print(features)

[[200 250 350 290 310 259 300 180 220 400]
 [  2   3   3   3   3   3   4   2   3   5]
 [180 190 240 200 230 195 250 160 210 300]]


In [3]:
# from Soudeh

import numpy as np

House_size = np.random.randint(100,500,10, dtype=int)
House_size = sorted(House_size, reverse=True)

House_rooms = np.random.choice(range(1,3), size=10, replace=True)
House_rooms = sorted(House_rooms, reverse= True)

House_price = np.random.choice(range(300_000, 1_000_000), size=10, replace=True)
House_price = sorted(House_price, reverse=True)

House_features = np.array([House_size, House_rooms, House_price])
House_features

array([[   472,    408,    394,    324,    309,    249,    190,    184,
           182,    170],
       [     2,      2,      2,      2,      2,      1,      1,      1,
             1,      1],
       [945601, 915116, 790625, 728594, 719480, 716458, 565103, 503910,
        395285, 351990]])

2- Transpose the array you have created, so that every line can represent features of one house.

In [6]:
features = features.T
print(features)

[[200   2 180]
 [250   3 190]
 [350   3 240]
 [290   3 200]
 [310   3 230]
 [259   3 195]
 [300   4 250]
 [180   2 160]
 [220   3 210]
 [400   5 300]]


3- Display the shape of the array and explain what it means.

In [7]:
features.shape
#The array has 10 rows and 3 columns

(10, 3)

4- Load the Earthquakes dataset. Export the dataset to an array as you covered in the previous lesson.

"\nwith open('earthquakes1970-2014.csv', 'r') as eq:\n    reader = csv.reader(eq)\n    data = np.array(list(reader)) #.dtype(float)\nprint(data[:3])\nprint(data.shape)\n"

In [16]:
# from Soudelh

import os

for Dir, Folders, Files in os.walk(os.getcwd()):
    for File in Files:
        if File == 'earthquakes1970-2014.csv':
            Path = os.path.join(Dir, File)
            print(Path)


In [18]:
import pandas as pd
data = pd.read_csv('earthquakes1970-2014.csv')
data.head()
 

DateTime  Latitude  Longitude  Depth  Magnitude MagType  \
0  1970/01/04 17:00:40.20    24.139    102.503   31.0        7.5      Ms   
1  1970/01/06 05:35:51.80    -9.628    151.458    8.0        6.2      Ms   
2  1970/01/08 17:12:39.10   -34.741    178.568  179.0        6.1      Mb   
3  1970/01/10 12:07:08.60     6.825    126.737   73.0        6.1      Mb   
4  1970/01/16 08:05:39.00    60.280   -152.660   85.0        6.0      ML   

   NbStations  Gap  Distance  RMS Source       EventID  
0        90.0  NaN       NaN  0.0    NEI  1.970010e+09  
1        85.0  NaN       NaN  0.0    NEI  1.970011e+09  
2        59.0  NaN       NaN  0.0    NEI  1.970011e+09  
3        91.0  NaN       NaN  0.0    NEI  1.970011e+09  
4         0.0  NaN       NaN  NaN     AK           NaN

In [19]:
data.shape

(5304, 12)

5- Slice first 20 rows and column numbers 3, 5, 6, 7, 12. Then, assign the array you sliced to a variable.


In [22]:
data2 = data.iloc[:20, [2, 4, 5, 6, 11]]
data2.head()

Longitude  Magnitude MagType  NbStations       EventID
0    102.503        7.5      Ms        90.0  1.970010e+09
1    151.458        6.2      Ms        85.0  1.970011e+09
2    178.568        6.1      Mb        59.0  1.970011e+09
3    126.737        6.1      Mb        91.0  1.970011e+09
4   -152.660        6.0      ML         0.0           NaN

6- Display the row numbers where last values are equal to 4.5 or higher.


In [28]:
#last values are EventID, wrong question? I changed it to the values from Magnitude
data_5 = data['Magnitude']
print(data[data_5 >= 4.5]) 


                    DateTime  Latitude  Longitude   Depth  Magnitude MagType  \
0     1970/01/04 17:00:40.20   24.1390   102.5030   31.00        7.5      Ms   
1     1970/01/06 05:35:51.80   -9.6280   151.4580    8.00        6.2      Ms   
2     1970/01/08 17:12:39.10  -34.7410   178.5680  179.00        6.1      Mb   
3     1970/01/10 12:07:08.60    6.8250   126.7370   73.00        6.1      Mb   
4     1970/01/16 08:05:39.00   60.2800  -152.6600   85.00        6.0      ML   
...                      ...       ...        ...     ...        ...     ...   
5299  2013/12/01 06:29:57.80    2.0440    96.8261   20.00        6.0      Mw   
5300  2013/12/08 17:24:54.20   44.4438   149.1667   28.00        6.1      Mw   
5301  2013/12/17 23:38:08.10   20.7635   146.7599   16.06        6.2      Mw   
5302  2014/01/01 16:03:28.89  -13.8779   167.2434  187.00        6.5      Mw   
5303  2014/01/13 04:01:04.69   19.0014   -66.8478   28.00        6.4      Mw   

      NbStations   Gap  Distance   RMS 

7- Assign 1 to first row.


In [31]:
data.iloc[0] = 1
data.iloc[0]

DateTime        1
Latitude      1.0
Longitude     1.0
Depth         1.0
Magnitude     1.0
MagType         1
NbStations    1.0
Gap           1.0
Distance      1.0
RMS           1.0
Source          1
EventID       1.0
Name: 0, dtype: object

8- Save the final state of the array to disk. You are going to use this in the next assignment.


In [44]:
data.to_csv('earthquakes_saved', index=False)


9- Load the array you saved in the previous lesson from the disk.

In [45]:
data_new = pd.read_csv('earthquakes_saved')
data_new.head()
#data_saved = np.load('earthquakes_array.npy', allow_pickle=True)
#data_saved = data_saved[:,[1,2,3,4,6]]
#print(data_saved)

DateTime  Latitude  Longitude  Depth  Magnitude MagType  \
0                       1     1.000      1.000    1.0        1.0       1   
1  1970/01/06 05:35:51.80    -9.628    151.458    8.0        6.2      Ms   
2  1970/01/08 17:12:39.10   -34.741    178.568  179.0        6.1      Mb   
3  1970/01/10 12:07:08.60     6.825    126.737   73.0        6.1      Mb   
4  1970/01/16 08:05:39.00    60.280   -152.660   85.0        6.0      ML   

   NbStations  Gap  Distance  RMS Source       EventID  
0         1.0  1.0       1.0  1.0      1  1.000000e+00  
1        85.0  NaN       NaN  0.0    NEI  1.970011e+09  
2        59.0  NaN       NaN  0.0    NEI  1.970011e+09  
3        91.0  NaN       NaN  0.0    NEI  1.970011e+09  
4         0.0  NaN       NaN  NaN     AK           NaN

10- Display the mean and the standard deviation for each column.


In [46]:
data.mean()


/var/folders/3j/dhs8gmxj1wv7j6tk8_jzmv1c0000gn/T/ipykernel_98829/4080730010.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  data.mean()


Latitude      2.585998e+00
Longitude     4.462209e+01
Depth         7.426238e+01
Magnitude     6.367888e+00
NbStations    3.017570e+02
Gap           4.882081e+01
Distance      6.573099e+00
RMS           8.171163e-01
EventID       1.979933e+09
dtype: float64

In [47]:
data.std()

/var/folders/3j/dhs8gmxj1wv7j6tk8_jzmv1c0000gn/T/ipykernel_98829/2723740006.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  data.std()


Latitude      2.987148e+01
Longitude     1.247909e+02
Depth         1.290948e+02
Magnitude     4.252056e-01
NbStations    1.709842e+02
Gap           5.286080e+01
Distance      1.001230e+01
RMS           5.595743e-01
EventID       1.718992e+08
dtype: float64

11- Subtract 1, 25, 25, 10, 4 from columns in order. (Remember it can be dobe in one line of code.)


In [49]:
new = [1,25,25,10,4]
data_new_part = data_new[['Latitude', 'Longitude',
                          'Depth', 'Magnitude', 'NbStations']]
data_new_part.subtract(new)


Latitude  Longitude   Depth  Magnitude  NbStations
0       0.0000   -24.0000  -24.00       -9.0        -3.0
1     -10.6280   126.4580  -17.00       -3.8        81.0
2     -35.7410   153.5680  154.00       -3.9        55.0
3       5.8250   101.7370   48.00       -3.9        87.0
4      59.2800  -177.6600   60.00       -4.0        -4.0
...        ...        ...     ...        ...         ...
5299    1.0440    71.8261   -5.00       -4.0         NaN
5300   43.4438   124.1667    3.00       -3.9         NaN
5301   19.7635   121.7599   -8.94       -3.8         NaN
5302  -14.8779   142.2434  162.00       -3.5         NaN
5303   18.0014   -91.8478    3.00       -3.6         NaN

[5304 rows x 5 columns]

12- Multiply each element by 2. (Remember it can be done in one line of code.)

In [36]:
data_new * 2

Unnamed: 0                                      DateTime  Latitude  \
0              0                                            11    2.0000   
1              2  1970/01/06 05:35:51.801970/01/06 05:35:51.80  -19.2560   
2              4  1970/01/08 17:12:39.101970/01/08 17:12:39.10  -69.4820   
3              6  1970/01/10 12:07:08.601970/01/10 12:07:08.60   13.6500   
4              8  1970/01/16 08:05:39.001970/01/16 08:05:39.00  120.5600   
...          ...                                           ...       ...   
5299       10598  2013/12/01 06:29:57.802013/12/01 06:29:57.80    4.0880   
5300       10600  2013/12/08 17:24:54.202013/12/08 17:24:54.20   88.8876   
5301       10602  2013/12/17 23:38:08.102013/12/17 23:38:08.10   41.5270   
5302       10604  2014/01/01 16:03:28.892014/01/01 16:03:28.89  -27.7558   
5303       10606  2014/01/13 04:01:04.692014/01/13 04:01:04.69   38.0028   

      Longitude   Depth  Magnitude MagType  NbStations   Gap  Distance   RMS  \
0        2.0000    2.00        2.0      11         2.0   2.0       2.0  2.00   
1      302.9160   16.00       12.4    MsMs       170.0   NaN       NaN  0.00   
2      357.1360  358.00       12.2    MbMb       118.0   NaN       NaN  0.00   
3      253.4740  146.00       12.2    MbMb       182.0   NaN       NaN  0.00   
4     -305.3200  170.00       12.0    MLML         0.0   NaN       NaN   NaN   
...         ...     ...        ...     ...         ...   ...       ...   ...   
5299   193.6522   40.00       12.0    MwMw         NaN  54.0       2.0  1.78   
5300   298.3334   56.00       12.2    MwMw         NaN  52.0      10.0  1.98   
5301   293.5198   32.12       12.4    MwMw         NaN  28.0       8.0  1.48   
5302   334.4868  374.00       13.0    MwMw         NaN  28.0       8.0  1.34   
5303  -133.6956   56.00       12.8    MwMw         NaN  42.0       2.0  2.84   

      Source       EventID  
0         11  2.000000e+00  
1     NEINEI  3.940021e+09  
2     NEINEI  3.940022e+09  
3     NEINEI  3.940022e+09  
4       AKAK           NaN  
...      ...           ...  
5299    usus  4.026240e+09  
5300    usus  4.026242e+09  
5301    usus  4.026243e+09  
5302    usus  4.028020e+09  
5303    usus  4.028023e+09  

[5304 rows x 13 columns]