1- Create three lists representing house features, each list containing ten values. The first one for the house's size in square meters, the second one for rooms and last for price. Then, create an array combining these lists.

In [7]:
import numpy as np
size = [200,250,350,290,310,259,300,180,220,400]
rooms = [2,3,3,3,3,3,4,2,3,5]
price = [180,190,240,200,230,195,250,160,210,300]
features = np.array([size,rooms,price])
print(features)

[[200 250 350 290 310 259 300 180 220 400]
 [  2   3   3   3   3   3   4   2   3   5]
 [180 190 240 200 230 195 250 160 210 300]]


2- Transpose the array you have created, so that every line can represent features of one house.

In [8]:
features = features.T
print(features)

[[200   2 180]
 [250   3 190]
 [350   3 240]
 [290   3 200]
 [310   3 230]
 [259   3 195]
 [300   4 250]
 [180   2 160]
 [220   3 210]
 [400   5 300]]


3- Display the shape of the array and explain what it means.

In [9]:
features.shape
#The array has 10 rows and 3 columns

(10, 3)

For the following assignment, you are going to use Earthquakes [https://bootrain-lms-assets.s3.eu-central-1.amazonaws.com/bootrain-lms-static/datasets/Earthquakes.csv] dataset.

4- Load the Earthquakes dataset. Export the dataset to an array as you covered in the previous lesson.

In [58]:
import numpy as np
import csv

'''
with open('earthquakes1970-2014.csv', 'r') as eq:
    reader = csv.reader(eq)
    data = np.array(list(reader)) #.dtype(float)
print(data[:3])
print(data.shape)
'''


"\nwith open('earthquakes1970-2014.csv', 'r') as eq:\n    reader = csv.reader(eq)\n    data = np.array(list(reader)) #.dtype(float)\nprint(data[:3])\nprint(data.shape)\n"

5- Slice first 20 rows and column numbers 3, 5, 6, 7, 12. Then, assign the array you sliced to a variable.


In [61]:
sliced = data[:20, [2, 4, 5, 6, 11]]
print(sliced[:3])

[[102.503 7.5 'Ms' 90.0 1970010440.0]
 [151.458 6.2 'Ms' 85.0 1970010640.0]
 [178.568 6.1 'Mb' 59.0 1970010840.0]]


6- Display the row numbers where last values are equal to 4.5 or higher.


In [62]:
#last values are EventID, wrong question?
last = data[:, -1]
print(last)
print(np.where(last>=4.5))
#np.where(float(data[:,-1])>=4.5, axis=1)

[1970010440.0 1970010640.0 1970010840.0 ... 2013121720.0 2014010120.0
 2014011320.0]
(array([   0,    1,    2, ..., 5301, 5302, 5303]),)


7- Assign 1 to first row.


In [63]:
data[0]=1
print(data[0])

[1 1 1 1 1 1 1 1 1 1 1 1]


8- Save the final state of the array to disk. You are going to use this in the next assignment.


In [71]:
np.save('earthquakes_array', data)

9- Load the array you saved in the previous lesson from the disk.


In [99]:
data_saved = np.load('earthquakes_array.npy', allow_pickle=True)
data_saved = data_saved[:,[1,2,3,4,6]]
print(data_saved)

[[1 1 1 1 1]
 [-9.628 151.458 8.0 6.2 85.0]
 [-34.741 178.568 179.0 6.1 59.0]
 ...
 [20.7635 146.759899999999 16.06 6.2 nan]
 [-13.8779 167.2434 187.0 6.5 nan]
 [19.0014 -66.8478 28.0 6.4 nan]]


10- Display the mean and the standard deviation for each column.


In [101]:
print('Mean:',np.mean(data_saved,axis=0))


Mean: [2.5859975490196043 44.62208761312208 74.26238122171952 6.3678883861236075
 nan]


11- Subtract 1, 25, 25, 10, 4 from columns in order. (Remember it can be dobe in one line of code.)


In [103]:
new = [1,25,25,10,4]
data_saved + new


array([[2, 26, 26, 11, 5],
       [-8.628, 176.458, 33.0, 16.2, 89.0],
       [-33.741, 203.568, 204.0, 16.1, 63.0],
       ...,
       [21.7635, 171.759899999999, 41.06, 16.2, nan],
       [-12.8779, 192.2434, 212.0, 16.5, nan],
       [20.0014, -41.84780000000001, 53.0, 16.4, nan]], dtype=object)

12- Multiply each element by 2. (Remember it can be done in one line of code.)

In [102]:
data_saved * 2

array([[2, 2, 2, 2, 2],
       [-19.256, 302.916, 16.0, 12.4, 170.0],
       [-69.482, 357.136, 358.0, 12.2, 118.0],
       ...,
       [41.527, 293.519799999998, 32.12, 12.4, nan],
       [-27.7558, 334.4868, 374.0, 13.0, nan],
       [38.0028, -133.6956, 56.0, 12.8, nan]], dtype=object)