1- Create three lists representing house features, each list containing ten values. The first one for the house's size in square meters, the second one for rooms and last for price. Then, create an array combining these lists.

In [7]:
import numpy as np
size = [200,250,350,290,310,259,300,180,220,400]
rooms = [2,3,3,3,3,3,4,2,3,5]
price = [180,190,240,200,230,195,250,160,210,300]
features = np.array([size,rooms,price])
print(features)

[[200 250 350 290 310 259 300 180 220 400]
 [  2   3   3   3   3   3   4   2   3   5]
 [180 190 240 200 230 195 250 160 210 300]]


2- Transpose the array you have created, so that every line can represent features of one house.

In [8]:
features = features.T
print(features)

[[200   2 180]
 [250   3 190]
 [350   3 240]
 [290   3 200]
 [310   3 230]
 [259   3 195]
 [300   4 250]
 [180   2 160]
 [220   3 210]
 [400   5 300]]


3- Display the shape of the array and explain what it means.

In [9]:
features.shape
#The array has 10 rows and 3 columns

(10, 3)